#!/bin/zsh
set -euo pipefail
PROJECT_DIR="${0:A:h:h}"
INSTALL_DIR="$HOME/Library/Application Support/JobMonitor"
RUNTIME="$INSTALL_DIR/runtime"
VENV="$RUNTIME/.venv"
# A private instance keeps its config in a separate repository; point at it with
# JOB_MONITOR_CONFIG_SOURCE=/path/to/private-repo/config.
CONFIG_SOURCE="${JOB_MONITOR_CONFIG_SOURCE:-$PROJECT_DIR/config}"
mkdir -p "$HOME/Library/LaunchAgents" "$INSTALL_DIR" "$HOME/Library/Logs" "$RUNTIME/mac" "$RUNTIME/src" "$RUNTIME/config" "$RUNTIME/data"
cp "$PROJECT_DIR/requirements.txt" "$RUNTIME/requirements.txt"
cp "$PROJECT_DIR/mac/mac_agent.py" "$RUNTIME/mac/mac_agent.py"
cp "$PROJECT_DIR/mac/run_agent.sh" "$RUNTIME/mac/run_agent.sh"
cp "$PROJECT_DIR/mac/dashboard.py" "$RUNTIME/mac/dashboard.py"
# Shared dashboard assets (same UI as the fictional public demo).
rsync -a --delete "$PROJECT_DIR/web/" "$RUNTIME/web/"
cp "$PROJECT_DIR/mac/tracker.py" "$RUNTIME/mac/tracker.py"
cp "$PROJECT_DIR/mac/mail_sync.py" "$RUNTIME/mac/mail_sync.py"
cp "$PROJECT_DIR/mac/notifier.py" "$RUNTIME/mac/notifier.py"
cp "$PROJECT_DIR/src/email_history.py" "$RUNTIME/src/email_history.py"
cp "$PROJECT_DIR"/src/*.py "$RUNTIME/src/"
cp "$CONFIG_SOURCE"/*.yaml "$RUNTIME/config/"
cp "$PROJECT_DIR/mac/run_dashboard.sh" "$RUNTIME/mac/run_dashboard.sh"
cp "$PROJECT_DIR/mac/run_mail_sync.sh" "$RUNTIME/mac/run_mail_sync.sh"
cp "$PROJECT_DIR/mac/run_priority_monitor.sh" "$RUNTIME/mac/run_priority_monitor.sh"
chmod +x "$RUNTIME/mac/run_agent.sh" "$RUNTIME/mac/run_dashboard.sh" "$RUNTIME/mac/run_mail_sync.sh" "$RUNTIME/mac/run_priority_monitor.sh"
python3 -m venv "$VENV"
"$VENV/bin/pip" install -r "$RUNTIME/requirements.txt"
sed -e "s|__RUNTIME__|$RUNTIME|g" -e "s|__HOME__|$HOME|g" "$PROJECT_DIR/mac/com.jobmonitor.poll.plist.template" > "$HOME/Library/LaunchAgents/com.jobmonitor.poll.plist"
sed -e "s|__RUNTIME__|$RUNTIME|g" -e "s|__HOME__|$HOME|g" "$PROJECT_DIR/mac/com.jobmonitor.dashboard.plist.template" > "$HOME/Library/LaunchAgents/com.jobmonitor.dashboard.plist"
sed -e "s|__RUNTIME__|$RUNTIME|g" -e "s|__HOME__|$HOME|g" "$PROJECT_DIR/mac/com.jobmonitor.mail-sync.plist.template" > "$HOME/Library/LaunchAgents/com.jobmonitor.mail-sync.plist"
sed -e "s|__RUNTIME__|$RUNTIME|g" -e "s|__HOME__|$HOME|g" "$PROJECT_DIR/mac/com.jobmonitor.priority.plist.template" > "$HOME/Library/LaunchAgents/com.jobmonitor.priority.plist"
echo "Installed. Save the private repo name and fine-grained read-only token:"
echo "echo 'owner/private-repository' > '$HOME/Library/Application Support/JobMonitor/github_repo'"
echo "security add-generic-password -U -a $USER -s job-monitor-github-token -w 'TOKEN'"
echo "Then run:"
echo "launchctl bootstrap gui/$(id -u) $HOME/Library/LaunchAgents/com.jobmonitor.poll.plist"
echo "launchctl bootstrap gui/$(id -u) $HOME/Library/LaunchAgents/com.jobmonitor.dashboard.plist"
echo "launchctl bootstrap gui/$(id -u) $HOME/Library/LaunchAgents/com.jobmonitor.mail-sync.plist"
echo "launchctl bootstrap gui/$(id -u) $HOME/Library/LaunchAgents/com.jobmonitor.priority.plist"
echo "Dashboard: $PROJECT_DIR/.venv/bin/python $PROJECT_DIR/mac/dashboard.py"
