#!/bin/zsh
set -euo pipefail
PROJECT_DIR="${0:A:h:h}"
INSTALL_DIR="$HOME/Library/Application Support/JobMonitor"
RUNTIME="$INSTALL_DIR/runtime"
VENV="$RUNTIME/.venv"
mkdir -p "$HOME/Library/LaunchAgents" "$INSTALL_DIR" "$HOME/Library/Logs" "$RUNTIME/mac"
cp "$PROJECT_DIR/requirements.txt" "$RUNTIME/requirements.txt"
cp "$PROJECT_DIR/mac/mac_agent.py" "$RUNTIME/mac/mac_agent.py"
cp "$PROJECT_DIR/mac/run_agent.sh" "$RUNTIME/mac/run_agent.sh"
chmod +x "$RUNTIME/mac/run_agent.sh"
python3 -m venv "$VENV"
"$VENV/bin/pip" install -r "$RUNTIME/requirements.txt"
sed -e "s|__RUNTIME__|$RUNTIME|g" -e "s|__HOME__|$HOME|g" "$PROJECT_DIR/mac/com.jobmonitor.poll.plist.template" > "$HOME/Library/LaunchAgents/com.jobmonitor.poll.plist"
echo "Installed. Save the private repo name and fine-grained read-only token:"
echo "echo 'owner/private-repository' > '$HOME/Library/Application Support/JobMonitor/github_repo'"
echo "security add-generic-password -U -a $USER -s job-monitor-github-token -w 'TOKEN'"
echo "Then run:"
echo "launchctl bootstrap gui/$(id -u) $HOME/Library/LaunchAgents/com.jobmonitor.poll.plist"
echo "Dashboard: $PROJECT_DIR/.venv/bin/python $PROJECT_DIR/mac/dashboard.py"
