"""Build the public, fictional bootstrap from checked-in fixtures only."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "mac"))
from tracker import STAGE_ORDER, merge_tracker


def build() -> str:
    fixtures = json.loads((ROOT / "demo/fixtures.json").read_text())
    items = merge_tracker(fixtures["queue"], fixtures["history"], fixtures["statuses"])
    payload = {
        "mode": "demo",
        "snapshot": {
            "items": items,
            "stages": list(STAGE_ORDER),
            "snapshot_at": fixtures["snapshot_at"],
            "queue_updated_at": fixtures["snapshot_at"],
            "warnings": [],
        },
    }
    return (
        "// Generated by scripts/build_demo.py from fictional fixtures.\nwindow.TRACKER_BOOTSTRAP = "
        + json.dumps(payload, indent=2, sort_keys=True)
        + ";\n"
    )


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Fail when the generated demo is stale")
    args = parser.parse_args()
    destination = ROOT / "web/bootstrap.js"
    result = build()
    if args.check:
        if not destination.exists() or destination.read_text() != result:
            raise SystemExit("Demo is stale. Run python scripts/build_demo.py")
    else:
        destination.write_text(result)


if __name__ == "__main__":
    main()
