// Generated by scripts/build_demo.py from fictional fixtures.
window.TRACKER_BOOTSTRAP = {
  "mode": "demo",
  "snapshot": {
    "items": [
      {
        "age_hours": 20,
        "assessment": {
          "flags": [],
          "reasons": [
            "target term: summer 2027",
            "skills: python, sql, vba, pandas, analytics",
            "location: Remote US",
            "posted within 24 hours"
          ],
          "score": 46
        },
        "company": "Folio",
        "first_seen": "2026-10-03T12:00:00+00:00",
        "key": "demo-12",
        "location": "Remote",
        "source": "fictional_board",
        "status": "dismissed",
        "status_source": "manual",
        "title": "Business Intelligence Intern",
        "url": "https://example.com/jobs/DEMO-112"
      },
      {
        "assessment": {
          "flags": [],
          "reasons": [],
          "score": "\u2014"
        },
        "company": "Canopy",
        "events": [
          {
            "company_hint": "Canopy",
            "confidence": 0.94,
            "date": "Oct 5, 2026",
            "date_iso": "2026-10-05T14:00:00+00:00",
            "mailbox_account": "demo@example.test",
            "requisition_id": "DEMO-111",
            "role_hint": "Engineering Intern",
            "stage": "applied",
            "subject": "Canopy: applied update (fictional)"
          },
          {
            "company_hint": "Canopy",
            "confidence": 0.94,
            "date": "Oct 6, 2026",
            "date_iso": "2026-10-06T14:00:00+00:00",
            "mailbox_account": "demo@example.test",
            "requisition_id": "DEMO-111",
            "role_hint": "Engineering Intern",
            "stage": "rejected",
            "subject": "Canopy: rejected update (fictional)"
          }
        ],
        "key": "application-req-0aa9974cca597c8d7a00",
        "last_update": "Oct 6, 2026",
        "location": "",
        "status": "rejected",
        "status_source": "email",
        "title": "Engineering Intern",
        "url": ""
      },
      {
        "assessment": {
          "flags": [],
          "reasons": [],
          "score": "\u2014"
        },
        "company": "Index",
        "events": [
          {
            "company_hint": "Index",
            "confidence": 0.94,
            "date": "Oct 2, 2026",
            "date_iso": "2026-10-02T14:00:00+00:00",
            "mailbox_account": "demo@example.test",
            "requisition_id": "DEMO-108",
            "role_hint": "Software Intern",
            "stage": "applied",
            "subject": "Index: applied update (fictional)"
          },
          {
            "company_hint": "Index",
            "confidence": 0.94,
            "date": "Oct 3, 2026",
            "date_iso": "2026-10-03T14:00:00+00:00",
            "mailbox_account": "demo@example.test",
            "requisition_id": "DEMO-108",
            "role_hint": "Software Intern",
            "stage": "offer",
            "subject": "Index: offer update (fictional)"
          }
        ],
        "key": "application-req-ebb80039808d2edae4c1",
        "last_update": "Oct 3, 2026",
        "location": "",
        "status": "offer",
        "status_source": "email",
        "title": "Software Intern",
        "url": ""
      },
      {
        "age_hours": 70,
        "assessment": {
          "flags": [],
          "reasons": [
            "target term: 2027 internship",
            "skills: python, sql, pandas, git, data science, machine learning",
            "location: Remote US",
            "posted within 7 days"
          ],
          "score": 48
        },
        "company": "Forma",
        "events": [
          {
            "company_hint": "Forma",
            "confidence": 0.94,
            "date": "Oct 3, 2026",
            "date_iso": "2026-10-03T14:00:00+00:00",
            "mailbox_account": "demo@example.test",
            "requisition_id": "DEMO-101",
            "role_hint": "Product Analytics Intern",
            "stage": "applied",
            "subject": "Forma: applied update (fictional)"
          },
          {
            "company_hint": "Forma",
            "confidence": 0.94,
            "date": "Oct 4, 2026",
            "date_iso": "2026-10-04T14:00:00+00:00",
            "mailbox_account": "demo@example.test",
            "requisition_id": "DEMO-101",
            "role_hint": "Product Analytics Intern",
            "stage": "interview",
            "subject": "Forma: interview update (fictional)"
          }
        ],
        "first_seen": "2026-10-02T12:00:00+00:00",
        "key": "demo-01",
        "last_update": "Oct 4, 2026",
        "location": "Remote",
        "source": "fictional_board",
        "status": "interview",
        "status_source": "email",
        "title": "Product Analytics Intern",
        "url": "https://example.com/jobs/DEMO-101"
      },
      {
        "age_hours": 30,
        "assessment": {
          "flags": [],
          "reasons": [
            "target term: summer 2027",
            "role match: data science",
            "skills: python, sql, pandas, data science, machine learning",
            "company priority: Standard",
            "posted within 7 days"
          ],
          "score": 47
        },
        "company": "Northstar",
        "events": [
          {
            "company_hint": "Northstar",
            "confidence": 0.94,
            "date": "Oct 2, 2026",
            "date_iso": "2026-10-02T14:00:00+00:00",
            "mailbox_account": "demo@example.test",
            "requisition_id": "DEMO-100",
            "role_hint": "Data Science Intern",
            "stage": "applied",
            "subject": "Northstar: applied update (fictional)"
          },
          {
            "company_hint": "Northstar",
            "confidence": 0.94,
            "date": "Oct 3, 2026",
            "date_iso": "2026-10-03T14:00:00+00:00",
            "mailbox_account": "demo@example.test",
            "requisition_id": "DEMO-100",
            "role_hint": "Data Science Intern",
            "stage": "interview",
            "subject": "Northstar: interview update (fictional)"
          }
        ],
        "first_seen": "2026-10-01T12:00:00+00:00",
        "key": "demo-00",
        "last_update": "Oct 3, 2026",
        "location": "Boston, MA",
        "source": "fictional_board",
        "status": "interview",
        "status_source": "email",
        "title": "Data Science Intern",
        "url": "https://example.com/jobs/DEMO-100"
      },
      {
        "age_hours": 50,
        "assessment": {
          "flags": [],
          "reasons": [
            "target term: summer 2027",
            "role match: software engineering",
            "skills: python, java, backend, api",
            "location: New York",
            "company priority: Target",
            "posted within 7 days"
          ],
          "score": 63
        },
        "company": "Meridian",
        "events": [
          {
            "company_hint": "Meridian",
            "confidence": 0.94,
            "date": "Oct 4, 2026",
            "date_iso": "2026-10-04T14:00:00+00:00",
            "mailbox_account": "demo@example.test",
            "requisition_id": "DEMO-102",
            "role_hint": "Software Engineering Intern",
            "stage": "applied",
            "subject": "Meridian: applied update (fictional)"
          },
          {
            "company_hint": "Meridian",
            "confidence": 0.94,
            "date": "Oct 5, 2026",
            "date_iso": "2026-10-05T14:00:00+00:00",
            "mailbox_account": "demo@example.test",
            "requisition_id": "DEMO-102",
            "role_hint": "Software Engineering Intern",
            "stage": "assessment",
            "subject": "Meridian: assessment update (fictional)"
          }
        ],
        "first_seen": "2026-10-03T12:00:00+00:00",
        "key": "demo-02",
        "last_update": "Oct 5, 2026",
        "location": "New York, NY",
        "source": "fictional_board",
        "status": "assessment",
        "status_source": "email",
        "title": "Software Engineering Intern",
        "url": "https://example.com/jobs/DEMO-102"
      },
      {
        "age_hours": 6,
        "assessment": {
          "flags": [],
          "reasons": [
            "target term: summer 2027",
            "skills: python, tensorflow, fastapi, health data, machine learning",
            "location: California",
            "posted within 24 hours"
          ],
          "score": 54
        },
        "company": "Aster",
        "events": [
          {
            "company_hint": "Aster",
            "confidence": 0.94,
            "date": "Oct 3, 2026",
            "date_iso": "2026-10-03T14:00:00+00:00",
            "mailbox_account": "demo@example.test",
            "requisition_id": "DEMO-105",
            "role_hint": "ML Engineering Intern",
            "stage": "applied",
            "subject": "Aster: applied update (fictional)"
          },
          {
            "company_hint": "Aster",
            "confidence": 0.94,
            "date": "Oct 4, 2026",
            "date_iso": "2026-10-04T14:00:00+00:00",
            "mailbox_account": "demo@example.test",
            "requisition_id": "DEMO-105",
            "role_hint": "ML Engineering Intern",
            "stage": "assessment",
            "subject": "Aster: assessment update (fictional)"
          }
        ],
        "first_seen": "2026-10-01T12:00:00+00:00",
        "key": "demo-05",
        "last_update": "Oct 4, 2026",
        "location": "San Francisco, CA",
        "priority_program": {
          "id": "aster_fellows",
          "matched_alias": "aster fellows",
          "name": "Aster Fellows (fictional)",
          "official_source": false
        },
        "source": "fictional_board",
        "status": "assessment",
        "status_source": "email",
        "title": "ML Engineering Intern",
        "url": "https://jobs.example.net/aster/DEMO-105"
      },
      {
        "age_hours": 100,
        "assessment": {
          "flags": [],
          "reasons": [
            "target term: summer 2027",
            "skills: python, sql, pandas, git, data science, machine learning",
            "location: Remote US",
            "posted within 7 days"
          ],
          "score": 48
        },
        "company": "Daybreak",
        "events": [
          {
            "company_hint": "Daybreak",
            "confidence": 0.94,
            "date": "Oct 5, 2026",
            "date_iso": "2026-10-05T14:00:00+00:00",
            "mailbox_account": "demo@example.test",
            "requisition_id": "DEMO-115",
            "role_hint": "Product Analytics Intern",
            "stage": "applied",
            "subject": "Daybreak: applied update (fictional)"
          }
        ],
        "first_seen": "2026-10-01T12:00:00+00:00",
        "key": "demo-15",
        "last_update": "Oct 5, 2026",
        "location": "Remote",
        "source": "fictional_board",
        "status": "applied",
        "status_source": "email",
        "title": "Product Analytics Intern",
        "url": "https://example.com/jobs/DEMO-115"
      },
      {
        "age_hours": 120,
        "assessment": {
          "flags": [],
          "reasons": [
            "target term: spring 2027",
            "skills: python, sql, r, quantitative, analytics, risk",
            "location: Chicago",
            "posted within 7 days"
          ],
          "score": 54
        },
        "company": "Parallel",
        "events": [
          {
            "company_hint": "Parallel",
            "confidence": 0.94,
            "date": "Oct 4, 2026",
            "date_iso": "2026-10-04T14:00:00+00:00",
            "mailbox_account": "demo@example.test",
            "requisition_id": "DEMO-106",
            "role_hint": "Analytics Intern",
            "stage": "applied",
            "subject": "Parallel: applied update (fictional)"
          }
        ],
        "first_seen": "2026-10-02T12:00:00+00:00",
        "key": "demo-06",
        "last_update": "Oct 4, 2026",
        "location": "Chicago, IL",
        "source": "fictional_board",
        "status": "applied",
        "status_source": "email",
        "title": "Analytics Intern",
        "url": "https://example.com/jobs/DEMO-106"
      },
      {
        "age_hours": 80,
        "assessment": {
          "flags": [],
          "reasons": [
            "target term: summer 2027",
            "role match: research intern",
            "skills: python, pandas, quantitative, trading",
            "location: New York",
            "company priority: Reach",
            "posted within 7 days"
          ],
          "score": 55
        },
        "company": "Sonder Labs",
        "events": [
          {
            "company_hint": "Sonder Labs",
            "confidence": 0.94,
            "date": "Oct 4, 2026",
            "date_iso": "2026-10-04T14:00:00+00:00",
            "mailbox_account": "demo@example.test",
            "requisition_id": "DEMO-110",
            "role_hint": "Research Intern",
            "stage": "applied",
            "subject": "Sonder Labs: applied update (fictional)"
          }
        ],
        "first_seen": "2026-10-01T12:00:00+00:00",
        "key": "demo-10",
        "last_update": "Oct 4, 2026",
        "location": "New York, NY",
        "source": "fictional_board",
        "status": "applied",
        "status_source": "email",
        "title": "Research Intern",
        "url": "https://example.com/jobs/DEMO-110"
      },
      {
        "age_hours": 150,
        "assessment": {
          "flags": [],
          "reasons": [
            "target term: summer 2027",
            "skills: python, sql, r, vba, pandas, data science",
            "location: Remote US",
            "posted within 7 days"
          ],
          "score": 48
        },
        "company": "Latticeworks",
        "events": [
          {
            "company_hint": "Latticeworks",
            "confidence": 0.94,
            "date": "Oct 3, 2026",
            "date_iso": "2026-10-03T14:00:00+00:00",
            "mailbox_account": "demo@example.test",
            "requisition_id": "DEMO-109",
            "role_hint": "Data Analyst Intern",
            "stage": "applied",
            "subject": "Latticeworks: applied update (fictional)"
          }
        ],
        "first_seen": "2026-10-05T12:00:00+00:00",
        "key": "demo-09",
        "last_update": "Oct 3, 2026",
        "location": "Remote",
        "source": "fictional_board",
        "status": "applied",
        "status_source": "email",
        "title": "Data Analyst Intern",
        "url": "https://example.com/jobs/DEMO-109"
      },
      {
        "age_hours": 40,
        "assessment": {
          "flags": [],
          "reasons": [
            "target term: summer 2027",
            "skills: python, sql, figma, machine learning, analytics, api",
            "location: Texas",
            "posted within 7 days"
          ],
          "score": 50
        },
        "company": "Kindred",
        "first_seen": "2026-10-03T12:00:00+00:00",
        "key": "demo-07",
        "location": "Austin, TX",
        "source": "fictional_board",
        "status": "reviewing",
        "status_source": "manual",
        "title": "Product Intern",
        "url": "https://example.com/jobs/DEMO-107"
      },
      {
        "age_hours": 60,
        "assessment": {
          "flags": [
            "term not explicit"
          ],
          "reasons": [
            "role match: developer",
            "skills: python, javascript, sql, html, css, django",
            "location: New York",
            "posted within 7 days"
          ],
          "score": 50
        },
        "company": "Terrace",
        "first_seen": "2026-10-05T12:00:00+00:00",
        "key": "demo-14",
        "location": "New York, NY",
        "source": "fictional_board",
        "status": "reviewing",
        "status_source": "manual",
        "title": "Software Developer Intern",
        "url": "https://example.com/jobs/DEMO-114"
      },
      {
        "age_hours": 10,
        "assessment": {
          "flags": [],
          "reasons": [
            "target term: summer 2027",
            "skills: python, sql, analytics, database",
            "location: Seattle / Redmond",
            "company priority: Target",
            "posted within 24 hours"
          ],
          "score": 60
        },
        "company": "Orbit Labs",
        "first_seen": "2026-10-04T12:00:00+00:00",
        "key": "demo-03",
        "location": "Seattle, WA",
        "priority_program": {
          "id": "orbit_launch",
          "matched_alias": "orbit launch",
          "name": "Orbit Launch (fictional)",
          "official_source": true
        },
        "source": "fictional_board",
        "status": "ready",
        "status_source": "queue",
        "title": "Data Engineering Intern",
        "url": "https://example.com/jobs/DEMO-103"
      },
      {
        "age_hours": 18,
        "assessment": {
          "flags": [
            "term not explicit"
          ],
          "reasons": [
            "role match: research intern",
            "skills: python, sql, pandas, bert, data science, machine learning",
            "location: Remote US",
            "posted within 24 hours"
          ],
          "score": 48
        },
        "company": "Fieldwork",
        "first_seen": "2026-10-05T12:00:00+00:00",
        "key": "demo-04",
        "location": "Remote",
        "source": "fictional_board",
        "status": "ready",
        "status_source": "queue",
        "title": "Research Intern",
        "url": "https://example.com/jobs/DEMO-104"
      },
      {
        "age_hours": 14,
        "assessment": {
          "flags": [],
          "reasons": [
            "target term: summer 2027",
            "role match: data science",
            "skills: python, sql, pandas, health tech, data science, machine learning",
            "company priority: Standard",
            "posted within 24 hours"
          ],
          "score": 54
        },
        "company": "Waymark",
        "first_seen": "2026-10-04T12:00:00+00:00",
        "key": "demo-13",
        "location": "Atlanta, GA",
        "source": "fictional_board",
        "status": "ready",
        "status_source": "queue",
        "title": "Data Science Intern",
        "url": "https://example.com/jobs/DEMO-113"
      }
    ],
    "queue_updated_at": "2026-10-08T12:00:00+00:00",
    "snapshot_at": "2026-10-08T12:00:00+00:00",
    "stages": [
      "ready",
      "reviewing",
      "applied",
      "assessment",
      "interview",
      "offer",
      "rejected",
      "dismissed"
    ],
    "warnings": []
  }
};
