// Generated by scripts/build_demo.py from fictional fixtures.
window.TRACKER_BOOTSTRAP = {
  "mode": "demo",
  "snapshot": {
    "items": [
      {
        "assessment": {
          "flags": [],
          "reasons": [
            "Role aligns with the demo profile",
            "Relevant technical skills"
          ],
          "score": 74
        },
        "company": "Folio",
        "first_seen": "2026-10-03T12:00:00+00:00",
        "key": "demo-12",
        "location": "Remote",
        "source": "fictional_board",
        "status": "dismissed",
        "status_source": "manual",
        "title": "Business Intelligence Intern",
        "url": "https://example.com/jobs/DEMO-112"
      },
      {
        "assessment": {
          "flags": [],
          "reasons": [],
          "score": "\u2014"
        },
        "company": "Canopy",
        "events": [
          {
            "company_hint": "Canopy",
            "confidence": 0.94,
            "date": "Oct 5, 2026",
            "date_iso": "2026-10-05T14:00:00+00:00",
            "mailbox_account": "demo@example.test",
            "requisition_id": "DEMO-111",
            "role_hint": "Engineering Intern",
            "stage": "applied",
            "subject": "Canopy: applied update (fictional)"
          },
          {
            "company_hint": "Canopy",
            "confidence": 0.94,
            "date": "Oct 6, 2026",
            "date_iso": "2026-10-06T14:00:00+00:00",
            "mailbox_account": "demo@example.test",
            "requisition_id": "DEMO-111",
            "role_hint": "Engineering Intern",
            "stage": "rejected",
            "subject": "Canopy: rejected update (fictional)"
          }
        ],
        "key": "application-req-0aa9974cca597c8d7a00",
        "last_update": "Oct 6, 2026",
        "location": "",
        "status": "rejected",
        "status_source": "email",
        "title": "Engineering Intern",
        "url": ""
      },
      {
        "assessment": {
          "flags": [],
          "reasons": [],
          "score": "\u2014"
        },
        "company": "Index",
        "events": [
          {
            "company_hint": "Index",
            "confidence": 0.94,
            "date": "Oct 2, 2026",
            "date_iso": "2026-10-02T14:00:00+00:00",
            "mailbox_account": "demo@example.test",
            "requisition_id": "DEMO-108",
            "role_hint": "Software Intern",
            "stage": "applied",
            "subject": "Index: applied update (fictional)"
          },
          {
            "company_hint": "Index",
            "confidence": 0.94,
            "date": "Oct 3, 2026",
            "date_iso": "2026-10-03T14:00:00+00:00",
            "mailbox_account": "demo@example.test",
            "requisition_id": "DEMO-108",
            "role_hint": "Software Intern",
            "stage": "offer",
            "subject": "Index: offer update (fictional)"
          }
        ],
        "key": "application-req-ebb80039808d2edae4c1",
        "last_update": "Oct 3, 2026",
        "location": "",
        "status": "offer",
        "status_source": "email",
        "title": "Software Intern",
        "url": ""
      },
      {
        "assessment": {
          "flags": [],
          "reasons": [
            "Role aligns with the demo profile",
            "Relevant technical skills"
          ],
          "score": 86
        },
        "company": "Forma",
        "events": [
          {
            "company_hint": "Forma",
            "confidence": 0.94,
            "date": "Oct 3, 2026",
            "date_iso": "2026-10-03T14:00:00+00:00",
            "mailbox_account": "demo@example.test",
            "requisition_id": "DEMO-101",
            "role_hint": "Product Analytics Intern",
            "stage": "applied",
            "subject": "Forma: applied update (fictional)"
          },
          {
            "company_hint": "Forma",
            "confidence": 0.94,
            "date": "Oct 4, 2026",
            "date_iso": "2026-10-04T14:00:00+00:00",
            "mailbox_account": "demo@example.test",
            "requisition_id": "DEMO-101",
            "role_hint": "Product Analytics Intern",
            "stage": "interview",
            "subject": "Forma: interview update (fictional)"
          }
        ],
        "first_seen": "2026-10-02T12:00:00+00:00",
        "key": "demo-01",
        "last_update": "Oct 4, 2026",
        "location": "Remote",
        "source": "fictional_board",
        "status": "interview",
        "status_source": "email",
        "title": "Product Analytics Intern",
        "url": "https://example.com/jobs/DEMO-101"
      },
      {
        "assessment": {
          "flags": [],
          "reasons": [
            "Role aligns with the demo profile",
            "Relevant technical skills"
          ],
          "score": 91
        },
        "company": "Northstar",
        "events": [
          {
            "company_hint": "Northstar",
            "confidence": 0.94,
            "date": "Oct 2, 2026",
            "date_iso": "2026-10-02T14:00:00+00:00",
            "mailbox_account": "demo@example.test",
            "requisition_id": "DEMO-100",
            "role_hint": "Data Science Intern",
            "stage": "applied",
            "subject": "Northstar: applied update (fictional)"
          },
          {
            "company_hint": "Northstar",
            "confidence": 0.94,
            "date": "Oct 3, 2026",
            "date_iso": "2026-10-03T14:00:00+00:00",
            "mailbox_account": "demo@example.test",
            "requisition_id": "DEMO-100",
            "role_hint": "Data Science Intern",
            "stage": "interview",
            "subject": "Northstar: interview update (fictional)"
          }
        ],
        "first_seen": "2026-10-01T12:00:00+00:00",
        "key": "demo-00",
        "last_update": "Oct 3, 2026",
        "location": "Boston, MA",
        "source": "fictional_board",
        "status": "interview",
        "status_source": "email",
        "title": "Data Science Intern",
        "url": "https://example.com/jobs/DEMO-100"
      },
      {
        "assessment": {
          "flags": [],
          "reasons": [
            "Role aligns with the demo profile",
            "Relevant technical skills"
          ],
          "score": 88
        },
        "company": "Meridian",
        "events": [
          {
            "company_hint": "Meridian",
            "confidence": 0.94,
            "date": "Oct 4, 2026",
            "date_iso": "2026-10-04T14:00:00+00:00",
            "mailbox_account": "demo@example.test",
            "requisition_id": "DEMO-102",
            "role_hint": "Software Engineering Intern",
            "stage": "applied",
            "subject": "Meridian: applied update (fictional)"
          },
          {
            "company_hint": "Meridian",
            "confidence": 0.94,
            "date": "Oct 5, 2026",
            "date_iso": "2026-10-05T14:00:00+00:00",
            "mailbox_account": "demo@example.test",
            "requisition_id": "DEMO-102",
            "role_hint": "Software Engineering Intern",
            "stage": "assessment",
            "subject": "Meridian: assessment update (fictional)"
          }
        ],
        "first_seen": "2026-10-03T12:00:00+00:00",
        "key": "demo-02",
        "last_update": "Oct 5, 2026",
        "location": "New York, NY",
        "source": "fictional_board",
        "status": "assessment",
        "status_source": "email",
        "title": "Software Engineering Intern",
        "url": "https://example.com/jobs/DEMO-102"
      },
      {
        "assessment": {
          "flags": [],
          "reasons": [
            "Role aligns with the demo profile",
            "Relevant technical skills"
          ],
          "score": 90
        },
        "company": "Aster",
        "events": [
          {
            "company_hint": "Aster",
            "confidence": 0.94,
            "date": "Oct 3, 2026",
            "date_iso": "2026-10-03T14:00:00+00:00",
            "mailbox_account": "demo@example.test",
            "requisition_id": "DEMO-105",
            "role_hint": "ML Engineering Intern",
            "stage": "applied",
            "subject": "Aster: applied update (fictional)"
          },
          {
            "company_hint": "Aster",
            "confidence": 0.94,
            "date": "Oct 4, 2026",
            "date_iso": "2026-10-04T14:00:00+00:00",
            "mailbox_account": "demo@example.test",
            "requisition_id": "DEMO-105",
            "role_hint": "ML Engineering Intern",
            "stage": "assessment",
            "subject": "Aster: assessment update (fictional)"
          }
        ],
        "first_seen": "2026-10-01T12:00:00+00:00",
        "key": "demo-05",
        "last_update": "Oct 4, 2026",
        "location": "San Francisco, CA",
        "priority_program": {
          "name": "Summer 2027 cohort",
          "official_source": false
        },
        "source": "fictional_board",
        "status": "assessment",
        "status_source": "email",
        "title": "ML Engineering Intern",
        "url": "https://example.com/jobs/DEMO-105"
      },
      {
        "assessment": {
          "flags": [],
          "reasons": [
            "Role aligns with the demo profile",
            "Relevant technical skills"
          ],
          "score": 80
        },
        "company": "Daybreak",
        "events": [
          {
            "company_hint": "Daybreak",
            "confidence": 0.94,
            "date": "Oct 5, 2026",
            "date_iso": "2026-10-05T14:00:00+00:00",
            "mailbox_account": "demo@example.test",
            "requisition_id": "DEMO-115",
            "role_hint": "Product Analytics Intern",
            "stage": "applied",
            "subject": "Daybreak: applied update (fictional)"
          }
        ],
        "first_seen": "2026-10-01T12:00:00+00:00",
        "key": "demo-15",
        "last_update": "Oct 5, 2026",
        "location": "Remote",
        "source": "fictional_board",
        "status": "applied",
        "status_source": "email",
        "title": "Product Analytics Intern",
        "url": "https://example.com/jobs/DEMO-115"
      },
      {
        "assessment": {
          "flags": [],
          "reasons": [
            "Role aligns with the demo profile",
            "Relevant technical skills"
          ],
          "score": 83
        },
        "company": "Parallel",
        "events": [
          {
            "company_hint": "Parallel",
            "confidence": 0.94,
            "date": "Oct 4, 2026",
            "date_iso": "2026-10-04T14:00:00+00:00",
            "mailbox_account": "demo@example.test",
            "requisition_id": "DEMO-106",
            "role_hint": "Analytics Intern",
            "stage": "applied",
            "subject": "Parallel: applied update (fictional)"
          }
        ],
        "first_seen": "2026-10-02T12:00:00+00:00",
        "key": "demo-06",
        "last_update": "Oct 4, 2026",
        "location": "Chicago, IL",
        "source": "fictional_board",
        "status": "applied",
        "status_source": "email",
        "title": "Analytics Intern",
        "url": "https://example.com/jobs/DEMO-106"
      },
      {
        "assessment": {
          "flags": [],
          "reasons": [
            "Role aligns with the demo profile",
            "Relevant technical skills"
          ],
          "score": 87
        },
        "company": "Sonder Labs",
        "events": [
          {
            "company_hint": "Sonder Labs",
            "confidence": 0.94,
            "date": "Oct 4, 2026",
            "date_iso": "2026-10-04T14:00:00+00:00",
            "mailbox_account": "demo@example.test",
            "requisition_id": "DEMO-110",
            "role_hint": "Research Intern",
            "stage": "applied",
            "subject": "Sonder Labs: applied update (fictional)"
          }
        ],
        "first_seen": "2026-10-01T12:00:00+00:00",
        "key": "demo-10",
        "last_update": "Oct 4, 2026",
        "location": "New York, NY",
        "source": "fictional_board",
        "status": "applied",
        "status_source": "email",
        "title": "Research Intern",
        "url": "https://example.com/jobs/DEMO-110"
      },
      {
        "assessment": {
          "flags": [],
          "reasons": [
            "Role aligns with the demo profile",
            "Relevant technical skills"
          ],
          "score": 82
        },
        "company": "Latticeworks",
        "events": [
          {
            "company_hint": "Latticeworks",
            "confidence": 0.94,
            "date": "Oct 3, 2026",
            "date_iso": "2026-10-03T14:00:00+00:00",
            "mailbox_account": "demo@example.test",
            "requisition_id": "DEMO-109",
            "role_hint": "Data Analyst Intern",
            "stage": "applied",
            "subject": "Latticeworks: applied update (fictional)"
          }
        ],
        "first_seen": "2026-10-05T12:00:00+00:00",
        "key": "demo-09",
        "last_update": "Oct 3, 2026",
        "location": "Remote",
        "source": "fictional_board",
        "status": "applied",
        "status_source": "email",
        "title": "Data Analyst Intern",
        "url": "https://example.com/jobs/DEMO-109"
      },
      {
        "assessment": {
          "flags": [
            "Verify graduation window"
          ],
          "reasons": [
            "Role aligns with the demo profile",
            "Relevant technical skills"
          ],
          "score": 79
        },
        "company": "Kindred",
        "first_seen": "2026-10-03T12:00:00+00:00",
        "key": "demo-07",
        "location": "Austin, TX",
        "source": "fictional_board",
        "status": "reviewing",
        "status_source": "manual",
        "title": "Product Intern",
        "url": "https://example.com/jobs/DEMO-107"
      },
      {
        "assessment": {
          "flags": [
            "Verify graduation window"
          ],
          "reasons": [
            "Role aligns with the demo profile",
            "Relevant technical skills"
          ],
          "score": 85
        },
        "company": "Terrace",
        "first_seen": "2026-10-05T12:00:00+00:00",
        "key": "demo-14",
        "location": "New York, NY",
        "source": "fictional_board",
        "status": "reviewing",
        "status_source": "manual",
        "title": "Software Intern",
        "url": "https://example.com/jobs/DEMO-114"
      },
      {
        "assessment": {
          "flags": [
            "Verify graduation window"
          ],
          "reasons": [
            "Role aligns with the demo profile",
            "Relevant technical skills"
          ],
          "score": 94
        },
        "company": "Orbit Labs",
        "first_seen": "2026-10-04T12:00:00+00:00",
        "key": "demo-03",
        "location": "Seattle, WA",
        "priority_program": {
          "name": "Summer 2027 cohort",
          "official_source": true
        },
        "source": "fictional_board",
        "status": "ready",
        "status_source": "queue",
        "title": "Data Engineering Intern",
        "url": "https://example.com/jobs/DEMO-103"
      },
      {
        "assessment": {
          "flags": [],
          "reasons": [
            "Role aligns with the demo profile",
            "Relevant technical skills"
          ],
          "score": 84
        },
        "company": "Fieldwork",
        "first_seen": "2026-10-05T12:00:00+00:00",
        "key": "demo-04",
        "location": "Remote",
        "source": "fictional_board",
        "status": "ready",
        "status_source": "queue",
        "title": "Research Intern",
        "url": "https://example.com/jobs/DEMO-104"
      },
      {
        "assessment": {
          "flags": [],
          "reasons": [
            "Role aligns with the demo profile",
            "Relevant technical skills"
          ],
          "score": 89
        },
        "company": "Waymark",
        "first_seen": "2026-10-04T12:00:00+00:00",
        "key": "demo-13",
        "location": "Atlanta, GA",
        "source": "fictional_board",
        "status": "ready",
        "status_source": "queue",
        "title": "Data Science Intern",
        "url": "https://example.com/jobs/DEMO-113"
      }
    ],
    "queue_updated_at": "2026-10-08T12:00:00+00:00",
    "snapshot_at": "2026-10-08T12:00:00+00:00",
    "stages": [
      "ready",
      "reviewing",
      "applied",
      "assessment",
      "interview",
      "offer",
      "rejected",
      "dismissed"
    ],
    "warnings": []
  }
};
